### ISSUE TITLE
Comments shown on edition pages

### ISSUE THREAD

**Issue by jamiefolsom** [SHOREdevelopers/COVE#63]
See at bottom of this text -- can we remove the field, bullet, and "Cancel/Save" links?

<img width="750" alt="screenshot 2017-11-08 14 59 34" src="https://user-images.githubusercontent.com/882377/32571463-7a372b08-c495-11e7-90b2-cfbd96baeee1.png">

**Comment by daverett** [comment]
Thanks for the reminder. Fixed via https://github.com/SHOREdevelopers/COVE/commit/6bedcd294a1edef6598b4e6548f6d1ceea42b404
